// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Test.Models;

#nullable disable

namespace Test.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260603061120_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Test.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Công nghệ phần mềm"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Khoa học máy tính"
                        },
                        new
                        {
                            Id = 3,
                            Name = "An toàn thông tin"
                        });
                });

            modelBuilder.Entity("Test.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Lecturer")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Credits = 3,
                            Image = "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=500&auto=format&fit=crop&q=60",
                            Lecturer = "TS. Nguyễn Văn A",
                            Name = "Lập trình C# cơ bản"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Credits = 4,
                            Image = "https://images.unsplash.com/photo-1605379399642-870262d3d051?w=500&auto=format&fit=crop&q=60",
                            Lecturer = "ThS. Trần Thị B",
                            Name = "Cấu trúc dữ liệu và giải thuật"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Credits = 3,
                            Image = "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=500&auto=format&fit=crop&q=60",
                            Lecturer = "TS. Lê Hoàng C",
                            Name = "Lập trình Web với ASP.NET Core"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Credits = 3,
                            Image = "https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=500&auto=format&fit=crop&q=60",
                            Lecturer = "PGS.TS. Phạm Văn D",
                            Name = "Cơ sở dữ liệu"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Credits = 3,
                            Image = "https://images.unsplash.com/photo-1504639725590-34d0984388bd?w=500&auto=format&fit=crop&q=60",
                            Lecturer = "ThS. Vũ Minh E",
                            Name = "Phân tích và thiết kế hệ thống"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Credits = 3,
                            Image = "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=500&auto=format&fit=crop&q=60",
                            Lecturer = "TS. Đặng Quang F",
                            Name = "Nhập môn An toàn thông tin"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Credits = 4,
                            Image = "https://images.unsplash.com/photo-1531297484001-80022131f5a1?w=500&auto=format&fit=crop&q=60",
                            Lecturer = "GS.TS. Nguyễn Hải G",
                            Name = "Trí tuệ nhân tạo"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Credits = 3,
                            Image = "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=500&auto=format&fit=crop&q=60",
                            Lecturer = "ThS. Trịnh Văn H",
                            Name = "Mạng máy tính"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            Credits = 3,
                            Image = "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=500&auto=format&fit=crop&q=60",
                            Lecturer = "ThS. Bùi Thị I",
                            Name = "Phát triển ứng dụng di động"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            Credits = 3,
                            Image = "https://images.unsplash.com/photo-1531403009284-440f080d1e12?w=500&auto=format&fit=crop&q=60",
                            Lecturer = "TS. Hoàng Văn J",
                            Name = "Mẫu thiết kế phần mềm"
                        });
                });

            modelBuilder.Entity("Test.Models.Course", b =>
                {
                    b.HasOne("Test.Models.Category", "Category")
                        .WithMany("Courses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Test.Models.Category", b =>
                {
                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
